# Generated by Django 4.1 on 2023-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comentario_email_alter_comentario_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=300),
        ),
    ]
