# Generated by Django 4.1.3 on 2023-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_etiqueta_post_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='blog.etiqueta'),
        ),
    ]
